name: kubawalinski
favicon: null
layout_spectrum: 0.8640843681059778
typography_spectrum: 0.3885635619517416
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7907022435683757
  lightness: 0.3411843217909336
  saturation: 0.5354325957596302
  rhythmicContrast: 0.9131331674288958
purpose: []
